### PR TITLE
README: Mention the SossMLJ work

### PR DESCRIPTION
**Pull request by DilumAluthge**
I made the changes in `README.jmd`, and then I weaved `README.jmd` with `doctype = "github"` to generate `README.md`.

### CODE REVIEW

**Comment by cscherrer** [comment]
Thanks! Looks like it killed the SymPy stuff though?

Also, check are failing, is this a GG thing? Maybe we need to depend on its master branch?

**Comment by DilumAluthge** [comment]
I think part of the issue is that RNG output is not expected to be stable across different Julia versions.

Let me first make the PR to switch from Travis to GitHub Actions. We'll get tests passing in that PR, and merge it, and then we can rebase this.

**Comment by DilumAluthge** [comment]
How about this: we keep the doctests only for the latest version of Julia?

The alternative would be to figure out how to use https://github.com/rfourquet/StableRNGs.jl in the doctests. StableRNGs are (mostly) stable across Julia versions.

**Comment by cscherrer** [comment]
That sounds good, but I don't know how to make it work. Feel free to have a go at it if you do 🙂

**Comment by DilumAluthge** [comment]
> That sounds good, but I don't know how to make it work. Feel free to have a go at it if you do 🙂

Yeah I also have no idea 😂 

I think the short term plan is to get doctests working on Julia 1.5, and then only run them on Julia 1.5.

Long term we can try to figure out StableRNGs.

This week or next week, I'll make a PR that encompasses both the GitHub Actions stuff, and also fixes the test suite.

**Comment by cscherrer** [comment]
@DilumAluthge sorry for the delay, I think we can merge this and then straighten out the doctests

**Pull request merged**
