### PR TITLE
[WIP] Improvements to HMC sampling

### PR DESCRIPTION
**Pull request by sethaxen**
This PR is a work-in-progress. It begins to implement some of the improvements in #69. In its current state, it just makes sure that the user can:
1. Specify their own RNG
2. Completely tune Dynamic HMC via `kwargs`
3. Specify their own AD backend

Currently, this breaks `stream`. It looks like ResumableFunctions doesn't like `dynamicHMC`'s keyword arguments.

I'm still playing with a wrapper for `JointDistribution` to let it be used directly with dynamicHMC functions for full customizability.

It would be nice if the user could get back warm-up samples and stats. Thoughts on an interface for that?

Wherever this ends up, I'd like to give `advancedHMC` the same interface and (maybe) output types.

### CODE REVIEW

**Comment by sethaxen** [comment]
> At a high level, is the update here just to add RNG as an argument, or is there more to it?

No, it also makes the DynamicHMC mostly completely customizable. Specifically, all `kwargs` are forwarded to `mcmc_with_warmup` and `mcmc_keep_warmup`. I say "mostly" because the warmup samples and statistics aren't returned. Lastly, it lets you change `method` and specify a different backend for AD.

> I think the RNG is important to make available, but we should keep a method that uses a sensible default and then calls the RNG version.

Yup, that's here too:

https://github.com/cscherrer/Soss.jl/blob/5d3c8d5868e2c0b3bf503a453e7a9002ec92bf2c/src/inference/dynamicHMC.jl#L69-L71

In fact, the example in README.jmd still works.

**Comment by sethaxen** [comment]
I also ran JuliaFormatter.jl on the code because I could.

**Comment by cscherrer** [comment]
Ok I think I see now. This looks good to me, think it's ready to squash&merge?

**Comment by sethaxen** [comment]
Yes except for the break to streaming. I don't know how to fix that because I don't know what features the resumable functions don't like. A later PR can handle custom types and such.

**Comment by cscherrer** [comment]
Great! I don't think anyone is using the streaming stuff yet. I'll merge with dev, and have a look at patching up stream soon.

Thanks Seth!

**Pull request merged**
