### PR TITLE
[WIP] Specify sample size when sampling with particles

### PR DESCRIPTION
**Pull request by sethaxen**
Currently this doesn't work. Here's an example:

```julia
julia> using Soss;

julia> mod = @model (J) begin
           x ~ Normal() |> iid(J)
       end;

julia> p = particles(mod(J = 3); N = 5)
ERROR: UndefVarError: N not defined
Stacktrace:
 [1] getproperty at ./Base.jl:13 [inlined]
 [2] macro expansion at /Users/saxen/.julia/packages/GeneralizedGenerated/NDqgV/src/closure_conv.jl:121 [inlined]
 [3] _particles(::Type{TypeEncoding(Main)}, ::Model{NamedTuple{(:J,),T} where T<:Tuple,TypeEncoding(begin
    x ~ Normal() |> iid(J)
end),TypeEncoding(Main)}, ::NamedTuple{(:J,),Tuple{Int64}}, ::Val{5}) at /Users/saxen/.julia/packages/GeneralizedGenerated/NDqgV/src/closure_conv.jl:121
 [4] #particles#163 at /Users/saxen/projects/Soss.jl/src/particles.jl:60 [inlined]
 [5] (::Soss.var"#kw##particles")(::NamedTuple{(:N,),Tuple{Int64}}, ::typeof(particles), ::Soss.JointDistribution{NamedTuple{(:J,),Tuple{Int64}},NamedTuple{(:J,),T} where T<:Tuple,TypeEncoding(begin
    x ~ Normal() |> iid(J)
end),TypeEncoding(Main)}) at ./none:0
 [6] top-level scope at REPL[3]:1

julia> mod = @model (N) begin
           x ~ Normal() |> iid(N)
       end;

julia> p = particles(mod(N = 3); N = 5)
(N = 3, x = Particles{Float64,3}[0.0 ± 0.97, 0.0 ± 0.97, 0.0 ± 0.97])

julia> p.x[1]
Part3(0.0 ± 0.967)
```

It appears `N` is somehow being extracted from the `JointDistribution` and passed to `parts`. Hence when the model doesn't have an `N`, an error is thrown, and when it does, the keyword `N` passed to `particles` is ignored.

I suspect I'm doing something silly with the generalized generated function `_particles`. There are other funny things:

```julia
julia> p.x[1].particles
3-element Array{Float64,1}:
 -0.9674215661017014
  0.9674215661017014
  0.0               

julia> p.x[2].particles
3-element Array{Float64,1}:
 -0.9674215661017014
  0.9674215661017014
  0.0               

julia> p.x[3].particles
3-element Array{Float64,1}:
  0.0               
  0.9674215661017014
 -0.9674215661017014
```

@cscherrer any insights?

### CODE REVIEW

**Comment by cscherrer** [comment]
Yep, that's because it's inside a quote. You can see what it's generating like this:
```julia
julia> Soss.sourceParticles()(mod, 100)
quote
    x = parts(iid(J, Normal()); N=N)
    (J = J, x = x)
end
```

If you change it to 
```julia
export sourceParticles
function sourceParticles() 
        
    function(m::Model, _N::Int)
        _m = canonical(m)
        proc(_m, st::Assign)  = :($(st.x) = $(st.rhs))
        proc(_m, st::Sample)  = :($(st.x) = parts($(st.rhs); _N=$_N))
        proc(_m, st::Return)  = :(return $(st.rhs))
        proc(_m, st::LineNumber) = nothing

        vals = map(x -> Expr(:(=), x,x),variables(_m)) 

        wrap(kernel) = @q begin
            $kernel
            $(Expr(:tuple, vals...))
        end

        buildSource(_m, proc, wrap) |> flatten
    end
end
```
you get
```julia
julia> Soss.sourceParticles()(mod, 100)
quote
    x = parts(iid(J, Normal()); _N=100)
    (J = J, x = x)
end
```
I like to lead quoted things with underscores; we'll ask the user not to use variable names like this. We should probably have something more descriptive that `_N` though, or if we have an unnamed variable (`parts(dist, N)` instead of `parts(dist; N=N)`) we could sidestep the issue.

There's a second issue here, that generated functions are weird. To define 
```julia
@gg M function f(x::T)
    # do stuff
end
```

you have to work in terms of `x`, knowing full well when you say `x` it's going to hear `T`. Well, unless you're in a quote; then it will pass to the generated code so it really will be `x`. It's super weird.

**Comment by cscherrer** [comment]
Hang tight, I might have a fix

**Comment by cscherrer** [comment]
:)

```julia
julia> mod = @model (J) begin
                  x ~ Normal() |> iid(J)
              end;
julia> particles(mod(J=3))
(J = 3, x = Particles{Float64,1000}[8.28e-17 ± 1.0, 8.83e-17 ± 1.0, 6.97e-17 ± 1.
0])

julia> particles(mod(J=3),50)
(J = 3, x = Particles{Float64,50}[-8.88e-18 ± 1.0, -8.88e-18 ± 1.0, 4.44e-18 ± 1.0])
```

**Comment by sethaxen** [comment]
There's still something funny going on here.

```julia
julia> using Soss, Random

julia> Random.seed!(42);

julia> mod = @model (J) begin
           x ~ Normal() |> iid(J)
       end;

julia> p = particles(mod(J=3), 5)
(J = 3, x = Particles{Float64,5}[-4.44e-17 ± 0.98, -4.44e-17 ± 0.98, -4.44e-17 ± 0.98])
```

Those means and standard deviations are suspiciously close to the true values for sample size of 5.

```julia
julia> p.x[1].particles
5-element Array{Float64,1}:
  0.5244005127080407
  0.0               
 -1.2815515655446004
  1.2815515655446004
 -0.5244005127080409
```

The sampled values are symmetrical, and the true mean is included. Does `particles` not produce a random sample?

**Comment by cscherrer** [comment]
It uses systematic sampling, basically quantiles with some random offset. Any single sampling done this way is plausible as an actual random sample, but leads to lower variance estimators.

**Comment by sethaxen** [comment]
Oh, that's really interesting. I see now that MonteCarloMeasurements does that. 

Okay, it looks like `For` is doing something weird here:

```julia
julia> using Soss

julia> mod = @model (J) begin
          x ~ Normal()
          y ~ For(J) do _
              Normal(x)
          end
       end;

julia> p = particles(mod(J=3), 10)
(J = 3, x = -6.66e-17 ± 0.99, y = -8.88e-17 ± 0.98)

julia> p.x
Part10(-6.661e-17 ± 0.989)

julia> p.y
Part10(-8.882e-17 ± 0.978)
```

`y` should be a `Vector{<:Particles}`.

**Comment by cscherrer** [comment]
Good catch! Currently this is calling
```julia
parts(d::For, N::Int=DEFAULT_SAMPLE_SIZE) = parts.(d.f.(d.θ...), N)
```

This behaves differently based on the type parameters:

```julia
julia> d = For(1:5) do _ Normal() end
For{var"#7#8",Tuple{UnitRange{Int64}},Normal{Float64},Float64}(var"#7#8"(), (1:5,))

julia> d.f.(d.θ...)
5-element Array{Normal{Float64},1}:
 Normal{Float64}(μ=0.0, σ=1.0)
 Normal{Float64}(μ=0.0, σ=1.0)
 Normal{Float64}(μ=0.0, σ=1.0)
 Normal{Float64}(μ=0.0, σ=1.0)
 Normal{Float64}(μ=0.0, σ=1.0)

julia> d = For(5) do _ Normal() end
For{var"#9#10",Tuple{Int64},Normal{Float64},Float64}(var"#9#10"(), (5,))

julia> d.f.(d.θ...)
Normal{Float64}(μ=0.0, σ=1.0)
```

We need to fix the latter

**Comment by cscherrer** [comment]
Ok I think this does it:
```julia
function parts(d::For{F,Tuple{I}}, N::Int=DEFAULT_SAMPLE_SIZE) where {F <: Function, I <: Integer}
    parts.(d.f.(Base.OneTo.(d.θ)...), N)
end
```
So now

```julia
julia> d = For(5) do _ Normal() end
For{var"#15#16",Tuple{Int64},Normal{Float64},Float64}(var"#15#16"(), (5,))

julia> parts(d)
5-element Array{Particles{Float64,1000},1}:
 9.37e-17 ± 1.0
 8.13e-17 ± 1.0
 9.29e-17 ± 1.0
 8.57e-17 ± 1.0
 8.36e-17 ± 1.0
```

**Comment by sethaxen** [comment]
Awesome, thanks for fixing that! What's the intended difference between `For(1:5)` and `For(5)`? I think I just used the latter because I saw it in an example.

**Comment by cscherrer** [comment]
There's currently no difference, having both available is just a result of my trying to figure out the right way to do things. I think the most common use cases we need to support are

- `For(N1, N2, ... , Nk) do ... end`
- `For(eachindex(x)) do ... end`
- `For(eachrow(x)) do ... end`

Also, Soss is now very modular, so there's really no need for this to be Soss-specific. [There's a PR](https://github.com/TuringLang/DistributionsAD.jl/pull/13) to bring this into DistributionsAD; it'd be great to bring in things like `iid` as well.

**Comment by sethaxen** [comment]
Is the `For(N1, N2, ... , Nk) do ... end` case equivalent to looping over the `N`s? If so, the `For(N) do ... end` case is confusing because it's ambiguous whether it should have one value `N` or all values `Base.OneTo(N)`. Anyways, that tripped us up here, and here's another case where the behavior is not quite right:

```julia
julia> using Soss

julia> mod = @model (J) begin
          x ~ For(1:J) do _
              Normal()
          end
       end;

julia> p = dynamicHMC(mod(J=3), NamedTuple()) |> particles
(x = Particles{Float64,1000}[0.058 ± 0.98, -0.0307 ± 0.99, -0.0156 ± 1.0],)

julia> mod = @model (J) begin
          x ~ For(J) do _
              Normal()
          end
       end;

julia> p = dynamicHMC(mod(J=3), NamedTuple()) |> particles
(x = Particles{Float64,1000}[0.138 ± 1.0],)
```

My suggested change is to get rid of the interpretation of `For(N::Integer)...` as being the same as `For(Base.OneTo(N))...`.

**Comment by sethaxen** [comment]
Also, I love that `For` and maybe `iid` are moving to DistributionsAD. I thought the `|> iid` combinator was some syntactic sugar until last night I realized that `iid` is just another distribution and that's the usual piping syntax. Really nice!

**Comment by cscherrer** [comment]
I was thinking maybe `N` and `1:N` should lead to the same struct (we could add a test to ensure that). What do you mean by "get rid of the interpretation of [`N`] and [`1:N`] as being the same..."? That sounds like you're suggesting they should mean different things, am I misunderstanding?

And thanks for the `iid` props, I was really happy with how that worked out too. BTW I sometimes see you write

```julia
x ~ For(J) do _
              Normal()
          end
```

Do you use it that way often? In principle this should be equivalent to `iid`, but the independence information doesn't get to the compiler, so it may be less efficient (haven't tested this)

**Comment by sethaxen** [comment]
> I was thinking maybe `N` and `1:N` should lead to the same struct (we could add a test to ensure that). What do you mean by "get rid of the interpretation of [`N`] and [`1:N`] as being the same..."? That sounds like you're suggesting they should mean different things, am I misunderstanding?

Unless I'm misunderstanding `For(5, 6) do i ... end`  will result in `i` looping through `(5, 6)`. But  `For(5) do i ... end` will as you propose result in `i` looping through `1:5`. This seems unecessarily confusing, when it's consistent with the usual use of `for` for the user to write `For(1:5)`. I'm imagining cases like this

```julia
julia> mod = @model (inds) begin
          y ~ For(inds...) do i
             Normal(i, i^2)
          end
       end;

julia> particles(mod(inds=(5,6)))
(inds = (5, 6), y = 5.0 ± 25.0)

julia> particles(mod(inds=(5,)))
(inds = (5,), y = 5.0 ± 25.0)

julia> particles(mod(inds=1:5))
(inds = 1:5, y = 1.0 ± 1.0)
```

A user might expect the 2nd example to behave more like the first. After all, they passed a tuple and may not know how many items are in it. But it would behave like the last. But as you can see, we found another bug in addition to the `dynamicHMC` bug above. `y` has the wrong shape for all examples above. (should have lengths of 2, 5, and 5, respectively).

> BTW I sometimes see you write
> 
> ```julia
> x ~ For(J) do _
>               Normal()
>           end
> ```
> 
> Do you use it that way often?

No, just for constructing MWEs. :)

**Pull request merged**
