### PR TITLE
more methods for `For`

### PR DESCRIPTION
**Pull request by cscherrer**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@cscherrer Can you bump the patch version number? That way, as soon as this PR is merged, we can make a new release.

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
Bump @cscherrer 

Is this good to be merged?

**Comment by DilumAluthge** [comment]
Also, I think we should probably uncheck the "required" checkbox for the codecov checks in the branch protection settings for Soss.jl.

It's fine in SossMLJ.jl, since there is relatively little code, so it's easy to stay at 100% code coverage.

But getting the codecov checks to always pass in Soss.jl is going to be annoying.

**Comment by cscherrer** [comment]
> Is this good to be merged?

Not yet, I'll have time later this week to look closely at this again, just to be sure we're good to go.

> Also, I think we should probably uncheck the "required" checkbox for the codecov checks in the branch protection settings for Soss.jl.

Agreed. But at the same time, I'd like to be more disciplined about our process. Just added https://github.com/cscherrer/Soss.jl/issues/207 about this for more discussion

**Comment by cscherrer** [comment]
@DilumAluthge I think we can close this when this works:

```julia
function check_for_methods()
    for indices in [3, 1:3, (j for j in 1:3), [1,2,3]]
        d = For(i -> Normal(0.0, i), indices)

        println(indices)
        println(logpdf(d, rand(d)))
        println(logpdf(d, rand.(collect(d))))
        println()
    end

    for indices in [(2,3), (1:2,1:3), ((i,j) for 1 in 1:2, j in 1:3), rand(2,3)]
        d = For((i,j) -> Normal(i,j), indices)

        println(indices)
        println(logpdf(d, rand(d)))
        println(logpdf(d, rand.(collect(d))))
        println()
    end
end
```

**Comment by cscherrer** [comment]
It works! :)

```julia
julia> check_for_methods()
3
-6.460988738751976
-5.442709523666219

1:3
-5.100787069459405
-6.5778054826465855

Base.Generator{UnitRange{Int64},typeof(identity)}(identity, 1:3)
-5.7333391318322855
-7.416961129000436

[1, 2, 3]
-4.782591141191571
-5.5655010862880125

[0.21599201539821267 0.2685965434463282 0.6617757204631687; 0.8528112185768761 0.037596134893601585 0.5856529980204188]
-0.6011048938750998
0.03149988054081376

(2, 3)
-12.29022192292546
-11.418846957193036

(1:2, 1:3)
-10.177608665489013
-11.00932756682801
```

Just need to add this as a test and we can merge

**Comment by cscherrer** [comment]
Ok I've added it. There's no `@test` as such, just a `@testset` that needs to not error out

**Comment by DilumAluthge** [comment]
2 questions:
1. Would you consider this to be a breaking change? It looks like a return type changed - would you consider that to be part of the public API? It's a judgment call.
2. Looks like tests are failing?

**Comment by cscherrer** [comment]
Hmm, I thought it must have been failing before, but it may be a breaking change making them fail. Sorry if I was too hasty about this. I'll look into it

**Pull request merged**
