### PR TITLE
first doctests

### PR DESCRIPTION
**Pull request by millerjoey**
I added the setup code and a couple examples/doctests and the documentation for `prune` and `prior` to start us off. Note that all of the doctests are considered one test; I'm not yet sure if that can be changed:
```julia
Test Summary: | Pass  Total
Doctests      |    1      1
   Testing Soss tests passed 
```
Have a look and let me know if it seems alright.

Edit: Oops, look like I also committed my version of the readme. Sorry for the the performance regression :laughing:

### CODE REVIEW

**Comment by cscherrer** [comment]
This is great, thanks @millerjoey! 

Doctests pass, but it says it only runs one. And it looks like `?prior` give the docstring correctly but `?prune` doesn't work. It looks like the difference here is that `prune` has two tests. Maybe only one is allowed? I'll try combining them into one doctest.

Finally, the current setup for test dependencies in Soss is... adventurous. There's new way to do this that I think is really nice:
https://julialang.github.io/Pkg.jl/v1/creating-packages/#Adding-tests-to-the-package-1

so e.g. there's an entirely separate `test/Project.toml`. I recently learned that this pattern is more cutting-edge than I had thought, and in some cases it can cause problems with dependencies. But... maybe it'll be fine? I think let's stick with this for now and consider reverting to the "classic" setup if we need to.

**Comment by millerjoey** [comment]
Happy to break the ice on this ;)

> Doctests pass, but it says it only runs one.

Right, but if you introduce an error in either, it should cause the test to fail. It seems to treat all the doctests like there's only one `@test`, even if they're for different functions. Maybe there's a workaround?

> And it looks like `prior` give the docstring correctly but `prune` doesn't work.

Oh, hmm. It looks like it's working for me, although it shows the examples exactly as-is (and includes the `using Soss` which I'm not sure is necessary, especially repeated):
```
help?> prune
search: prune isupperbounded process_running set_comparison_function product_distribution PGeneralizedGaussian

  prune(m, xs...; simplify = true)

  Returns a model transformed by removing xs... and all variables that depend on xs.... If simplify = true,
  unneeded arguments are also removed. Use simplify = false to leave arguments unaffected.

  Example
  ≡≡≡≡≡≡≡≡≡

  using Soss
  m = @model n begin
      α ~ Gamma()
      β ~ Gamma()
      θ ~ Beta(α,β)
      x ~ Binomial(n, θ)
  end;
  prune(m, :θ)
  
  # output
  @model begin
          β ~ Gamma()
          α ~ Gamma()
      end

  using Soss
  m = @model n begin
      α ~ Gamma()
      β ~ Gamma()
      θ ~ Beta(α,β)
      x ~ Binomial(n, θ)
  end;
  prune(m, :n)
  
  # output
  @model begin
          β ~ Gamma()
          α ~ Gamma()
          θ ~ Beta(α, β)
      end
```

I think the [REPL format](https://juliadocs.github.io/Documenter.jl/stable/man/doctests/#REPL-Examples-1) is nicer and more standard, but I can't get it to work. It errors `ERROR: UndefVarError: m not defined`.

Gotcha, yeah. Seems like a good idea to keep the deps separate.

**Comment by cscherrer** [comment]
I think there may be some inconsistencies in Documenter. I was trying `doctest(Soss, fix=true)`, but I was getting some namespace complaints, which `using Soss` fixed. 

The `m not defined` thing seems related to this? Each doctest block is evaluated in its own module:
https://juliadocs.github.io/Documenter.jl/stable/man/doctests/#Preserving-Definitions-Between-Blocks-1

**Comment by v-a-s-a** [comment]
I am also able to get these running and build the docs locally. The results look pretty slick.

FWIW, I also ran into some namespace complaints when building docs, but not running doctests. Those were fixed by adding `DocMeta.setdocmeta!(Soss, :DocTestSetup, :(using Soss); recursive=true)
` to the top of `docs/make.jl`.

**Comment by cscherrer** [comment]
Let's merge this into `dev` so we can see if Travis will render the docs. Once we we get things working there we can merge to master and get ready for the next release

**Comment by millerjoey** [comment]
> The `m not defined` thing seems related to this?

I don't think so; it was defined and used in a single block. I'll see if I can replicate the issue and come back to this if we want to change the format.

**Pull request merged**
